kind: pipeline
name: default

steps:
- name: deploy
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build . -t privy:1.0

trigger:
  branch:
  - master
  event:
  - push
 
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
