kind: pipeline
name: default

steps:
- name: deploy
  image: docker
  commands:
  - docker build . -t privy:1.0
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock

trigger:
  branch:
  - master
  event:
  - push
 