kind: pipeline
name: privy

steps:
- name: build
  image: golang:alpine
  commands:
  - go mod tidy
  - go mod vendor
  - go build
  - go test

 - name: deploy
   image: golang:alpine
   commands:
    docker build . -t privy:1.0
    trigger:
    branch:
    - master
    event:
    - push
 

