kind: pipeline
name: default

steps:
- name: deploy
  image: golang:alpine
  commands:
  - apk apt-get update
  - apk update 
  - apk upgrade 
  - apk add git
  - go mod tidy
  - go mod vendor
  - CGO_ENABLED=0 GOOS=linux go build
  - nohup ./privyID &

trigger:
  branch:
  - master
  event:
  - push
 
