kind: pipeline
name: privy

steps:
- name: build
  image: plugins/docker
  commands:
   - docker build . -t privy:1.0

- name: deploy
   image: plugins/docker
   commands:
    - docker run -d -it --name privy privy:1.0
   
 trigger:
    branch:
    - master
    event:
    - push