kind: pipeline
name: privy

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test

 - name: deploy
   image: alpine
   commands:
    - go mod tidy
    - go mod vendor
    - go build 
    - ./privy

    
    trigger:
    branch:
    - master
    event:
    - push
 