kind: pipeline
name: privy

steps:

- name: build
  image: golang
  commands:
  - go build
  - go test

 - name: deploy
   image: golang/alpine
   commands:
    - go mod tidy
    - go mod vendor
    - go build 
    - ./privyID
    trigger:
    branch:
    - master
    event:
    - push
  volumes:
  - name: docker
    path: /var/run/docker.sock

